### ISSUE TITLE
Packaging of the project

### ISSUE THREAD

**Issue by sidharthanup** [stonezwr/TSSL-BP#1]
Hi,

I was working with implementing TSSL-BP on [bindsnet](https://github.com/BindsNET/bindsnet). It would be really helpful to import the modules here to use it. @stonezwr Is it possible for you to push a setup script (setup.py) for packaging the repo? Uploading to PyPI would also be desirable.

**Comment by stonezwr** [comment]
Hi, 

Thanks for your suggestion. We are still working on the code and improving its efficiency. Once we have a stable version, we'll package the repo.

Thanks.

**Comment by sidharthanup** [comment]
Thanks! That would be helpful
