### ISSUE TITLE
how to import N-MNIST?

### ISSUE THREAD

**Issue by ROY-SNN** [stonezwr/TSSL-BP#3]
Hello, I'm a student in school. I've used all three of the other data, but I don't  know how to import N-MNIST? I use NMNIST_Converter.m（NMNIST_Converter('Train', 1,2000)）, i find it just ouput the A folder named '2312_2000_stable' contains 10 '.dat' files which are all empty bytes. Is your.m function a reference to this site 'https://www.garrickorchard.com/datasets/n-mnis'?
Do I need to prepare any datasets in advance? Another question is, what's the difference between MINST_DVS(http://www2.imse-cnm.csic.es/caviar/MNIST_DVS/) and N-MINST？Is the MINST_DVS dataset useful to me?I've never been able to figure out the data on N-MINST. I really want to know.

**Comment by stonezwr** [comment]
Hello, 

Yes, the data is from https://www.garrickorchard.com/datasets/n-mnist. Please make sure the files in the preprocessing folder are put together with the Train and Test folder. The function I used is NMNIST_Converter('Train', 1, 3000) and NMNIST_Converter('Test', 1, 3000). Please let me know if you have any error messages.

I don't know the MINST_DVS. It seems it is from another work.

**Comment by ROY-SNN** [comment]
Does the training and Test folder refer to the regular MNIST data set? I don't understand the NMNIST_Converter function, which also doesn't have a place to read the regular MNIST data set. After I've executed this function, it doesn't seem right to print zero

>> NMNIST_Converter('Train', 1, 3000)
The average ignored spike per sample is 0.000000
The max spike train duration is 0
The median spike train duration is 0
>> NMNIST_Converter('Test', 1, 3000)
The average ignored spike per sample is 0.000000
The max spike train duration is 0
The median spike train duration is 0

**Comment by stonezwr** [comment]
1. Download everything in this dropbox link. https://www.dropbox.com/sh/tg2ljlbmtzygrag/AABrCc6FewNZSNsoObWJqY74a?dl=0

2. Copy NMNIST_Converter.m and RemoveNulls.m to the same folder.

3. Unzip Train.zip and Test.zip

4. Run NMNIST_Converter('Train', 1, 3000). You could see the progress bar. After it finish, you can run for the test again.

I checked the code just now. Everything is correct and it can generate the preprocessed data.

**Comment by stonezwr** [comment]
Hello,

I just realized I uploaded the wrong version of the conversion code. I have fixed the problem. Please try it again.

Thanks

**Comment by XDUSPONGE** [comment]
Hello, for the NMNIST dataset, for your loadNMNIST_Spiking.py, the shape is (batchsize, 2, 34, 34, 30)
However, for the NMNIST_CNN.yaml the input shape is (batch_size, 2, 32, 32, 30)
May be the yaml should be modified?
