### ISSUE TITLE
well-trained weight

### ISSUE THREAD

**Issue by Linxyhaha** [stonezwr/TSSL-BP#5]
Thank you for sharing your work! I really appreciate your great contribution to learning algorithm of snn, and the idea of inter and intra neuron dependencies is very impressive.
however, is there any approach to acquire your well-trained weight? lots of thanks

**Comment by stonezwr** [comment]
Hi,

Thanks for your interest in our work. The code below contains a checkpoint for the well-train CIFAR10 network.
https://www.dropbox.com/s/9uomas4evweub2q/TSSL-BP.zip?dl=0

You can run the code by 
`python main.py -config Networks/CIFAR10.yaml -gpu 0 -checkpoint checkpoint/ckpt.pth`

Please let me know if you have any other questions.

**Comment by Linxyhaha** [comment]
Thank you very much.

**Comment by lostlose** [comment]
Thank you very much for sharing your code！
I found that the training file you shared has expired. Could you please share it again? Thanks again

**Comment by chenjiefighting** [comment]
Hello, this project was deleted, can you share it again?
